"""initial schema

Revision ID: 452ae467d216
Revises: 
Create Date: 2026-09-22 10:59:12.344715

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '452ae467d216'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # Hand-written: autogenerate never emits extensions. pg_trgm backs the
    # typo-tolerant title search in the browse UI.
    op.execute("CREATE EXTENSION IF NOT EXISTS pg_trgm")

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('scrape_runs',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('trigger', sa.String(length=50), nullable=False),
    sa.Column('batch_id', sa.String(length=100), nullable=True),
    sa.Column('cost_usd', sa.Float(), server_default='0', nullable=False),
    sa.Column('stats', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.CheckConstraint("status IN ('running', 'success', 'partial', 'failed', 'budget_exceeded')", name=op.f('ck_scrape_runs_status')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_scrape_runs'))
    )
    op.create_table('sources',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('kind', sa.Enum('greenhouse', 'lever', 'ashby', 'workable', 'html', name='source_kind'), nullable=False),
    sa.Column('company_name', sa.String(length=200), nullable=False),
    sa.Column('company_slug', sa.String(length=200), nullable=False),
    sa.Column('board_token', sa.String(length=200), nullable=True),
    sa.Column('url', sa.Text(), nullable=True),
    sa.Column('enabled', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('config', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('render_mode', sa.String(length=20), server_default='auto', nullable=False),
    sa.Column('etag', sa.String(length=300), nullable=True),
    sa.Column('last_modified', sa.String(length=100), nullable=True),
    sa.Column('rate_limit_per_min', sa.SmallInteger(), server_default='30', nullable=False),
    sa.Column('consecutive_failures', sa.SmallInteger(), server_default='0', nullable=False),
    sa.Column('blocked_reason', sa.Text(), nullable=True),
    sa.Column('last_run_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("render_mode IN ('auto', 'http', 'browser')", name=op.f('ck_sources_render_mode')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_sources')),
    sa.UniqueConstraint('kind', 'board_token', name='uq_sources_kind_board_token')
    )
    op.create_index(op.f('ix_sources_company_slug'), 'sources', ['company_slug'], unique=False)
    op.create_table('jobs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('source_id', sa.Integer(), nullable=False),
    sa.Column('external_id', sa.String(length=255), nullable=False),
    sa.Column('url', sa.Text(), nullable=False),
    sa.Column('canonical_url', sa.Text(), nullable=True),
    sa.Column('apply_url', sa.Text(), nullable=True),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('title_normalized', sa.Text(), nullable=True),
    sa.Column('company', sa.String(length=200), nullable=False),
    sa.Column('location_raw', sa.Text(), nullable=True),
    sa.Column('department', sa.String(length=200), nullable=True),
    sa.Column('team', sa.String(length=200), nullable=True),
    sa.Column('employment_type', sa.String(length=100), nullable=True),
    sa.Column('description_html', sa.Text(), nullable=True),
    sa.Column('description_text', sa.Text(), nullable=True),
    sa.Column('posted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('posted_at_precision', sa.String(length=10), nullable=True),
    sa.Column('salary_min', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('salary_max', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('salary_currency', sa.String(length=3), nullable=True),
    sa.Column('salary_period', sa.String(length=10), nullable=True),
    sa.Column('salary_source', sa.String(length=10), server_default='none', nullable=False),
    sa.Column('seniority', sa.String(length=20), nullable=True),
    sa.Column('remote_policy', sa.String(length=20), nullable=True),
    sa.Column('remote_regions', postgresql.ARRAY(sa.Text()), nullable=True),
    sa.Column('tech_stack', postgresql.ARRAY(sa.Text()), nullable=True),
    sa.Column('years_experience_min', sa.SmallInteger(), nullable=True),
    sa.Column('years_experience_max', sa.SmallInteger(), nullable=True),
    sa.Column('location_city', sa.String(length=200), nullable=True),
    sa.Column('location_region', sa.String(length=200), nullable=True),
    sa.Column('location_country', sa.String(length=100), nullable=True),
    sa.Column('visa_sponsorship', sa.Boolean(), nullable=True),
    sa.Column('enrichment_flags', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('status', sa.Enum('open', 'stale', 'closed', name='job_status'), server_default='open', nullable=False),
    sa.Column('first_seen_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_seen_run_id', sa.BigInteger(), nullable=True),
    sa.Column('seen_count', sa.Integer(), server_default='1', nullable=False),
    sa.Column('missed_streak', sa.SmallInteger(), server_default='0', nullable=False),
    sa.Column('closed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('extraction_method', sa.String(length=20), nullable=False),
    sa.Column('extraction_model', sa.String(length=100), nullable=True),
    sa.Column('extraction_version', sa.SmallInteger(), server_default='1', nullable=False),
    sa.Column('enrichment_version', sa.SmallInteger(), nullable=True),
    sa.Column('enriched_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('content_hash', sa.String(length=64), nullable=False),
    sa.Column('dedup_key', sa.String(length=64), nullable=False),
    sa.Column('canonical_job_id', sa.UUID(), nullable=True),
    sa.Column('search_vector', postgresql.TSVECTOR(), sa.Computed("setweight(to_tsvector('english', coalesce(title, '')), 'A') || setweight(to_tsvector('english', coalesce(company, '')), 'B') || setweight(to_tsvector('english', coalesce(left(description_text, 100000), '')), 'C')", persisted=True), nullable=True),
    sa.CheckConstraint("extraction_method IN ('ats', 'jsonld', 'llm_html', 'llm_enrich')", name=op.f('ck_jobs_extraction_method')),
    sa.CheckConstraint("remote_policy IS NULL OR remote_policy IN ('onsite', 'hybrid', 'remote_country', 'remote_region', 'remote_global', 'unknown')", name=op.f('ck_jobs_remote_policy')),
    sa.CheckConstraint("salary_period IS NULL OR salary_period IN ('hour', 'day', 'week', 'month', 'year')", name=op.f('ck_jobs_salary_period')),
    sa.CheckConstraint("salary_source IN ('ats', 'regex', 'llm', 'none')", name=op.f('ck_jobs_salary_source')),
    sa.CheckConstraint("seniority IS NULL OR seniority IN ('intern', 'junior', 'mid', 'senior', 'staff', 'principal', 'lead', 'manager', 'director', 'executive', 'unknown')", name=op.f('ck_jobs_seniority')),
    sa.CheckConstraint('salary_min IS NULL OR salary_max IS NULL OR salary_min <= salary_max', name=op.f('ck_jobs_salary_range')),
    sa.ForeignKeyConstraint(['canonical_job_id'], ['jobs.id'], name=op.f('fk_jobs_canonical_job_id_jobs'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['source_id'], ['sources.id'], name=op.f('fk_jobs_source_id_sources'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_jobs')),
    sa.UniqueConstraint('source_id', 'external_id', name='uq_jobs_source_external')
    )
    op.create_index('ix_jobs_canonical_job_id', 'jobs', ['canonical_job_id'], unique=False)
    op.create_index('ix_jobs_content_hash', 'jobs', ['content_hash'], unique=False)
    op.create_index('ix_jobs_dedup_key', 'jobs', ['dedup_key'], unique=False)
    op.create_index('ix_jobs_open_posted', 'jobs', ['posted_at', 'id'], unique=False, postgresql_where=sa.text("status = 'open'"))
    op.create_index('ix_jobs_search_vector', 'jobs', ['search_vector'], unique=False, postgresql_using='gin')
    op.create_index('ix_jobs_tech_stack', 'jobs', ['tech_stack'], unique=False, postgresql_using='gin')
    op.create_table('raw_pages',
    sa.Column('body_sha256', sa.String(length=64), nullable=False),
    sa.Column('url', sa.Text(), nullable=False),
    sa.Column('source_id', sa.Integer(), nullable=True),
    sa.Column('fetched_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('http_status', sa.Integer(), nullable=True),
    sa.Column('content_type', sa.String(length=200), nullable=True),
    sa.Column('etag', sa.String(length=300), nullable=True),
    sa.Column('last_modified', sa.String(length=100), nullable=True),
    sa.Column('rendered', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('byte_len', sa.Integer(), nullable=True),
    sa.Column('body_path', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['source_id'], ['sources.id'], name=op.f('fk_raw_pages_source_id_sources'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('body_sha256', name=op.f('pk_raw_pages'))
    )
    op.create_index('ix_raw_pages_url', 'raw_pages', ['url'], unique=False)
    op.create_table('scrape_run_sources',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('run_id', sa.BigInteger(), nullable=False),
    sa.Column('source_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('jobs_found', sa.Integer(), server_default='0', nullable=False),
    sa.Column('jobs_new', sa.Integer(), server_default='0', nullable=False),
    sa.Column('jobs_updated', sa.Integer(), server_default='0', nullable=False),
    sa.Column('jobs_closed', sa.Integer(), server_default='0', nullable=False),
    sa.Column('http_requests', sa.Integer(), server_default='0', nullable=False),
    sa.Column('http_status', sa.Integer(), nullable=True),
    sa.Column('llm_calls', sa.Integer(), server_default='0', nullable=False),
    sa.Column('cost_usd', sa.Float(), server_default='0', nullable=False),
    sa.Column('error_class', sa.String(length=100), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.CheckConstraint("status IN ('pending', 'success', 'failed', 'suspect_drift', 'skipped_304', 'skipped_robots')", name=op.f('ck_scrape_run_sources_status')),
    sa.ForeignKeyConstraint(['run_id'], ['scrape_runs.id'], name=op.f('fk_scrape_run_sources_run_id_scrape_runs'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['source_id'], ['sources.id'], name=op.f('fk_scrape_run_sources_source_id_sources'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_scrape_run_sources')),
    sa.UniqueConstraint('run_id', 'source_id', name='uq_run_source')
    )
    op.create_index('ix_run_sources_source_id', 'scrape_run_sources', ['source_id'], unique=False)
    op.create_table('llm_calls',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('run_id', sa.BigInteger(), nullable=True),
    sa.Column('job_id', sa.UUID(), nullable=True),
    sa.Column('purpose', sa.String(length=40), nullable=False),
    sa.Column('model', sa.String(length=100), nullable=False),
    sa.Column('prompt_version', sa.SmallInteger(), nullable=False),
    sa.Column('batched', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('input_tokens', sa.Integer(), server_default='0', nullable=False),
    sa.Column('output_tokens', sa.Integer(), server_default='0', nullable=False),
    sa.Column('cache_read_tokens', sa.Integer(), server_default='0', nullable=False),
    sa.Column('cache_write_tokens', sa.Integer(), server_default='0', nullable=False),
    sa.Column('cost_usd', sa.Float(), server_default='0', nullable=False),
    sa.Column('latency_ms', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], name=op.f('fk_llm_calls_job_id_jobs'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['run_id'], ['scrape_runs.id'], name=op.f('fk_llm_calls_run_id_scrape_runs'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_llm_calls'))
    )
    op.create_index('ix_llm_calls_run_id', 'llm_calls', ['run_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_llm_calls_run_id', table_name='llm_calls')
    op.drop_table('llm_calls')
    op.drop_index('ix_run_sources_source_id', table_name='scrape_run_sources')
    op.drop_table('scrape_run_sources')
    op.drop_index('ix_raw_pages_url', table_name='raw_pages')
    op.drop_table('raw_pages')
    op.drop_index('ix_jobs_tech_stack', table_name='jobs', postgresql_using='gin')
    op.drop_index('ix_jobs_search_vector', table_name='jobs', postgresql_using='gin')
    op.drop_index('ix_jobs_open_posted', table_name='jobs', postgresql_where=sa.text("status = 'open'"))
    op.drop_index('ix_jobs_dedup_key', table_name='jobs')
    op.drop_index('ix_jobs_content_hash', table_name='jobs')
    op.drop_index('ix_jobs_canonical_job_id', table_name='jobs')
    op.drop_table('jobs')
    op.drop_index(op.f('ix_sources_company_slug'), table_name='sources')
    op.drop_table('sources')
    op.drop_table('scrape_runs')
    # ### end Alembic commands ###

    # Hand-written: dropping a table does NOT drop the native enum types it
    # used. Without these, downgrade-then-upgrade fails with "type already
    # exists" -- the classic Alembic enum trap.
    op.execute("DROP TYPE IF EXISTS job_status")
    op.execute("DROP TYPE IF EXISTS source_kind")
